name: Release drafter

# Push events to every tag not containing "/"
on:
  push:
    tags:
      - "*"

jobs:
  draft-a-release:
    name: Draft a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - id: get_data
        run: |
          echo "approvers=$(cat .github/CODEOWNERS | grep @ | tr -d '*\n ' | sed 's/@/,/g' | sed 's/,//1')" >> $GITHUB_OUTPUT
          echo "version=$(grep DRIVER_PACKAGE_VERSION src/CMakeLists.txt | grep -o -P '\d+\.\d+\.\d+\.\d+')" >> $GITHUB_OUTPUT
      - uses: trstringer/manual-approval@74d99dff7380e3e4b122d4ededcbca2b6ce59367 # v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ steps.get_data.outputs.approvers }}
          minimum-approvals: 2
          issue-title: 'Release ODBC driver version ${{ steps.get_data.outputs.version }}'
          issue-body: "Please approve or deny the release of ODBC Driver **TAG**: ${{ github.ref_name }}  **COMMIT**: ${{ github.sha }} **VERSION** : ${{ steps.get_data.outputs.version }} "
          exclude-workflow-initiator-as-approver: true

      - name: Download artifacts
        uses: dawidd6/action-download-artifact@bf251b5aa9c2f7eeb574a96ee720e24f801b7c11 # v6
        with:
          workflow: sql-odbc-main.yml
          commit: ${{github.sha}}
          workflow_conclusion: success

      - name: Rename and pack artifacts
        run: |
          # replace spaces by dashes in file names
          for i in *-installer/*; do mv "$i" "${i//\ /-}"; done
          tar -cvf artifacts.tar.gz *-installer

      - name: Draft a release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          draft: true
          generate_release_notes: true
          files: artifacts.tar.gz
